baseURL: https://marvelm.github.io
languageCode: en-CA
title: Marvel's Blog
theme: xmin
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩
permalinks:
  post: '/post/:year/:month/:day/:slug/'
  note: '/note/:year/:month/:day/:slug/'
menu:
  main:
    - name: Home
      url: /
      weight: 1
    #- name: About
      #url: /about/
      #weight: 2
    - name: Categories
      url: /categories/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4
    - name: Subscribe
      url: /index.xml
params:
  description: ''
  footer: >-

